name: HypeWatcher

on:
  schedule:
    - cron: "*/20 * * * *"   # every 20 minutes
  workflow_dispatch:         # allow manual runs from the Actions tab

concurrency:
  group: hypewatcher
  cancel-in-progress: false  # let a run finish; avoid overlap

jobs:
  run-hypewatcher:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run HypeWatcher
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID:   ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          python hype_watcher.py
